import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { motion } from "framer-motion";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { AnimatePresence, MotionConfig } from "framer-motion";
import TaskInput from "@/components/TaskInput";

// "Hello", "Good Morning", "Hola", "Guten Tag"
export default function Home() {

  var [greeting, setGreeting] = useState([
    {
      greeting : "Hello",
      color : "blue",
      font: "Times New Roman",
      fontSize: 12
    },
    {
      greeting : "Good morning",
      color : "red",
      font: "Courier New",
      fontSize: 24
    },

  ]);

  var clearGreeting = () => {
    setGreeting([]);
  }

  var addGreeting = () => {
    setGreeting(
      [
        {
          greeting : "Hello",
          color : "blue",
          font: "Times New Roman",
          fontSize: 12
        },
        {
          greeting : "Good morning",
          color : "red",
          font: "Courier New",
          fontSize: 24
        }
      ]
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.AppHeader}>
          <h1>Todo - Arnav</h1>
        </div>
        <div className={styles.Input}>
          <TaskInput></TaskInput>
        </div>
        <div className={styles.ItemsContainer}>
        </div>
      </main>
    </>
  );
}
